apiVersion: batch/v1
kind: Job
metadata:
  name: pg-migrate-web
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: migrate
          image: postgres:16
          env:
            - name: SRC_USER
              valueFrom:
                secretKeyRef:
                  name: external-db-credentials
                  key: username
            - name: SRC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: external-db-credentials
                  key: password
            - name: DST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: web.acid-web.credentials.postgresql.acid.zalan.do
                  key: password
          command:
            - bash
            - -c
            - |
              set -euo pipefail

              export PGPASSWORD="$SRC_PASSWORD"

              echo "=== pg_dump schema from external-db and apply on target DB ==="

              PGPASSWORD="$SRC_PASSWORD" pg_dump \
                -h external-db \
                -U "$SRC_USER" \
                -d web \
                -p 5432 \
                --schema-only \
                --format=plain \
                --no-owner \
                --no-privileges \
                --no-comments \
              | PGPASSWORD="$DST_PASSWORD" PGSSLMODE=require psql \
                -U web \
                -h acid-web \
                -d web \
                -p 5432

              echo "=== schema migration finished ===\n\n"
              echo "=== pg_dump data from external-db and apply on target DB ==="

              PGPASSWORD="$SRC_PASSWORD" pg_dump \
                -h external-db \
                -U "$SRC_USER" \
                -d web \
                -j 8 \
                -p 5432 \
                --data-only \
                --format=d \
                --verbose \
                --file=/dump

              PGPASSWORD="$DST_PASSWORD" PGSSLMODE=require pg_restore \
                -U web \
                -h acid-web \
                -d web \
                -j 8 \
                -p 5432 \
                --format=d \
                --verbose \
                /dump

              echo "=== data migration finished ==="
          volumeMounts:
            - name: dump
              mountPath: /dump
      volumes:
        - name: dump
          emptyDir: {}
