apiVersion: batch/v1
kind: Job
metadata:
  name: pg-migrate-web
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: migrate
          image: postgres:16
          env:
            - name: SRC_USER
              valueFrom:
                secretKeyRef:
                  name: external-db-credentials
                  key: username
            - name: SRC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: external-db-credentials
                  key: password
            - name: DST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xikolo-owner-user.xikolo-db.credentials.postgresql.acid.zalan.do
                  key: password
          command:
            - bash
            - -c
            - |
              set -euo pipefail

              export PGPASSWORD="$SRC_PASSWORD"

              echo "=== pg_dump from external-db ==="

              PGPASSWORD="$SRC_PASSWORD" pg_dump \
                -h external-db \
                -U "$SRC_USER" \
                -d web \
                -j 8 \
                -p 5432 \
                --no-owner \
                --no-privileges \
                --no-comments \
                --format=d \
                --verbose \
                --file=/dump

              echo "=== pg_restore to xikolo-db ==="

              PGPASSWORD="$DST_PASSWORD" PGSSLMODE=require pg_restore \
                -U xikolo_owner_user \
                -h xikolo-db \
                -d xikolo \
                -j 8 \
                -p 5432 \
                --no-owner \
                --no-privileges \
                --no-comments \
                --format=d \
                --verbose \
                /dump

              echo "=== data migration finished ==="
          volumeMounts:
            - name: dump
              mountPath: /dump
      volumes:
        - name: dump
          emptyDir:
            sizeLimit: 150Gi
