service:
  type: NodePort
  nodePort: 30080

extraEnvs:
  - name: SPILO_S3_BACKUP_BUCKET
    value: postgres-backups
  - name: SPILO_S3_BACKUP_PREFIX
    value: spilo/
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: s3-access
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: s3-access
        key: AWS_SECRET_ACCESS_KEY
  - name: AWS_DEFAULT_REGION
    valueFrom:
      secretKeyRef:
        name: s3-access
        key: AWS_DEFAULT_REGION
  - name: AWS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: s3-access
        key: AWS_ENDPOINT
