configKubernetes:
  pod_environment_secret: local-s3-credentials

configAwsOrGcp:
  aws_region: us-east-1
  wal_s3_bucket: postgres-backups

configLogicalBackup:
  logical_backup_provider: s3
  logical_backup_s3_access_key_id: minioadmin
  logical_backup_s3_bucket: postgres-backups
  logical_backup_s3_bucket_prefix: logical
  logical_backup_s3_endpoint: http://minio.default.svc.cluster.local:9000
  logical_backup_s3_region: us-east-1
  logical_backup_s3_retention_time: 7 days
  logical_backup_s3_secret_access_key: minioadmin123
  logical_backup_s3_sse: ""
  logical_backup_cronjob_environment_secret: local-s3-credentials
