configKubernetes:
  pod_environment_secret: s3-access

configAwsOrGcp:
  aws_region: us-east-1
  wal_s3_bucket: postgres-backups

configLogicalBackup:
  logical_backup_s3_bucket: postgres-backups
  logical_backup_s3_bucket_prefix: logical
  logical_backup_s3_retention_time: 7 days
  logical_backup_s3_sse: ""
  logical_backup_cronjob_environment_secret: s3-access
