apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-web
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - salando-control-plane
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  users:
    web: []
  databases:
    web: web
  postgresql:
    version: "16"
